// src/constants/initialCars.ts
import { type Vehicle } from '../types';

export const INITIAL_CARS: Record<string, Vehicle> = {
    escape2012: {
        id: 'escape2012',
        name: 'Ford Escape',
        modelYear: '2012',
        fuelType: 'Gasoline',
        price: '₱750,000',
        brand: 'Ford',
        transmission: '5-Speed Manual / 6-Speed Automatic',
        description: 'Front-Wheel Drive (FWD). AM/FM Radio, CD Player, AUX Input.',
        mileage: '45,000 KM',
        engine: '2.5L I4',
        hp: '171 hp',
        torque: '171 lb-ft',
        safety: 'Front Airbags, ABS',
        seating: '5 Seater',
        posted: '1 Day Ago',
        type: 'SUV',
        status: 'open',
        images: ['assets/suv_silver.png', 'assets/suv_gray.png', 'assets/suv_white.png'],
        date: '2026-03-27'
    },
    tesla_plaid: {
        id: 'tesla_plaid',
        name: 'Tesla Model S Plaid',
        modelYear: '2024',
        fuelType: 'Electric',
        price: '₱6,500,000',
        brand: 'Tesla',
        transmission: 'Single-Speed Fixed Gear',
        description: 'All-Wheel Drive (AWD). 1,020 hp, 0-60 mph in 1.99s. Autopilot.',
        mileage: '0 KM',
        engine: 'Tri-Motor Electric',
        hp: '1,020 hp',
        torque: '1,050 lb-ft',
        safety: 'Autopilot, 8 Cameras',
        seating: '5 Seater',
        posted: 'New Arrival',
        type: 'Electric Car',
        status: 'open',
        images: ['assets/tesla_plaid.png'],
        date: '2026-03-27'
    },
    porsche_taycan: {
        id: 'porsche_taycan',
        name: 'Porsche Taycan Turbo S',
        modelYear: '2024',
        fuelType: 'Electric',
        price: '₱12,500,000',
        brand: 'Porsche',
        transmission: '2-Speed Automatic',
        description: 'All-Wheel Drive (AWD). 800V Architecture, Taycan Soul, Matrix LED Headlights.',
        mileage: '0 KM',
        engine: 'Dual-Motor Electric',
        hp: '750 hp',
        torque: '774 lb-ft',
        safety: 'Porsche InnoDrive',
        seating: '4 Seater',
        posted: 'New Arrival',
        type: 'Electric Car',
        status: 'open',
        images: ['assets/porsche_taycan.png'],
        date: '2026-03-27'
    },
    escape2012_titanium: {
        id: 'escape2012_titanium',
        name: 'Ford Escape Titanium',
        modelYear: '2012',
        fuelType: 'Gasoline',
        price: '₱800,000',
        brand: 'Ford',
        transmission: '6-Speed Automatic',
        description: 'Front-Wheel Drive (FWD) / Optional AWD. Bluetooth, Premium Audio.',
        mileage: '38,000 KM',
        engine: '2.0L I4',
        hp: '240 hp',
        torque: '270 lb-ft',
        safety: 'Front/Side Airbags, ABS',
        seating: '5 Seater',
        posted: '1 Day Ago',
        type: 'SUV',
        status: 'open',
        images: ['assets/suv_gray.png', 'assets/suv_silver.png', 'assets/suv_white.png'],
        date: '2026-03-27'
    },
    livina2023: {
        id: 'livina2023',
        name: 'Nissan Livina VL',
        modelYear: '2023',
        fuelType: 'Gasoline',
        price: '₱1,100,000',
        brand: 'Nissan',
        transmission: '4-Speed Automatic',
        description: 'Front-Wheel Drive (FWD). 7-inch Display, CarPlay, Android Auto.',
        mileage: '15,000 KM',
        engine: '1.5L I4',
        hp: '103 hp',
        torque: '141 Nm',
        safety: 'Dual Airbags, ABS',
        seating: '7 Seater',
        posted: '2 Days Ago',
        type: 'SUV',
        status: 'open',
        images: ['assets/suv_white.png', 'assets/suv_silver.png', 'assets/suv_gray.png'],
        date: '2026-03-27'
    },
    civic_rs: {
        id: 'civic_rs',
        name: 'Honda Civic RS',
        modelYear: '2024',
        fuelType: 'Gasoline',
        price: '₱1,775,000',
        brand: 'Honda',
        transmission: 'CVT',
        description: 'Front-Wheel Drive. Honda SENSING, 9-inch Display, Bose Sound.',
        mileage: '5,000 KM',
        engine: '1.5L Turbo',
        hp: '178 hp',
        torque: '240 Nm',
        safety: 'Honda SENSING',
        seating: '5 Seater',
        posted: '3 Days Ago',
        type: 'Sedan',
        status: 'open',
        images: ['assets/sedan_black.png', 'assets/hatchback_red.png'],
        date: '2026-03-27'
    },
    mazda3_sport: {
        id: 'mazda3_sport',
        name: 'Mazda 3 Sport',
        modelYear: '2023',
        fuelType: 'Mild Hybrid',
        price: '₱1,500,000',
        brand: 'Mazda',
        transmission: '6-Speed Automatic',
        description: 'Front-Wheel Drive. 360° View Monitor, Signature KODO Design.',
        mileage: '12,000 KM',
        engine: '2.0L Mild Hybrid',
        hp: '153 hp',
        torque: '200 Nm',
        safety: 'i-ACTIVSENSE',
        seating: '5 Seater',
        posted: '4 Days Ago',
        type: 'Hatchback',
        status: 'open',
        images: ['assets/hatchback_red.png', 'assets/sedan_black.png'],
        date: '2026-03-27'
    },
    innova_v: {
        id: 'innova_v',
        name: 'Toyota Innova V',
        modelYear: '2022',
        fuelType: 'Diesel',
        price: '₱1,750,000',
        brand: 'Toyota',
        transmission: '6-Speed Automatic',
        description: 'Rear-Wheel Drive. Captain Seats, Ambient Lighting.',
        mileage: '28,000 KM',
        engine: '2.8L Turbo Diesel',
        hp: '174 hp',
        torque: '360 Nm',
        safety: 'Dual Airbags, ABS, VSC',
        seating: '7 Seater',
        posted: '5 Days Ago',
        type: 'Van',
        status: 'open',
        images: ['assets/suv_gray.png', 'assets/suv_silver.png'],
        date: '2026-03-27'
    },
    mustang_gt: {
        id: 'mustang_gt',
        name: 'Ford Mustang GT',
        modelYear: '2024',
        fuelType: 'Gasoline (V8)',
        price: '₱3,500,000',
        brand: 'Ford',
        transmission: '10-Speed Automatic',
        description: 'Rear-Wheel Drive (RWD). Track Apps, MagneRide.',
        mileage: '2,000 KM',
        engine: '5.0L V8',
        hp: '480 hp',
        torque: '560 Nm',
        safety: 'Ford Co-Pilot360',
        seating: '4 Seater',
        posted: '1 Day Ago',
        type: 'Sports Car',
        status: 'open',
        images: ['assets/sedan_black.png', 'assets/hatchback_red.png'],
        date: '2026-03-27'
    },
};
